logging.level:
#  root: DEBUG
  org.springframework.web.filter: DEBUG
  org.springframework.security.web.access: DEBUG
  org.springframework.web.client: DEBUG
  example.client.HelloClient: DEBUG
  org.apache.http: DEBUG

spring:
  application:
    name: admin-service

server:
  port: 8081


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

core-service:
  url: http://localhost:8080

security:
  oauth2:
    baseUrl: http://localhost:8080
    client:
      access-token-uri: http://localhost:8080/oauth/token
      client-id: 123
      client-secret: 123
      scope: admin
#      grant-type: client_credentials
    resource:
      id: service
      tokenInfoUri: http://localhost:8080/oauth/check_token