debug: true

logging.level:
#  root: DEBUG
#  org.springframework.web.filter: INFO
#  org.springframework.security.web.access: DEBUG
#  org.springframework.web.client: DEBUG
#  org.apache.http: DEBUG
  org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ebdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver