debug: true

logging.level:
#  root: DEBUG
  org.springframework.web.filter: DEBUG
  org.springframework.security.web.access: DEBUG
  org.springframework.web.client: DEBUG
  example.client.HelloClient: DEBUG
  org.apache.http: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver